symbol = input ("Enter one symbol: ")

print ()
print (symbol, symbol, symbol, symbol, symbol)
print ("   ", symbol)
print ("   ", symbol)
print ("   ", symbol)
print ("   ", symbol)
print (symbol, symbol, symbol)

print ()
print (symbol, symbol, symbol, symbol, symbol)
print (symbol, "     ", symbol)
print (symbol, "     ", symbol)
print (symbol, symbol, symbol, symbol, symbol)
print (symbol, "     ", symbol)
print (symbol, "     ", symbol)

print ()
print (symbol, "     ", symbol)
print (symbol, symbol, " ", symbol, symbol)
print (symbol, " ", symbol, " ", symbol)
print (symbol, "     ", symbol)
print (symbol, "     ", symbol)
print (symbol, "     ", symbol)

print ()
print (symbol, symbol, symbol, symbol, symbol)
print (symbol)
print (symbol, symbol, symbol)
print (symbol)
print (symbol)
print (symbol, symbol, symbol, symbol, symbol)

print ()
print (symbol, symbol, symbol, symbol, symbol)
print (symbol)
print (symbol, symbol, symbol, symbol, symbol)
print ("       ", symbol)
print ("       ", symbol)
print (symbol, symbol, symbol, symbol, symbol)
